/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWeekRouteImport } from './routes/_app/week'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiUploadthingFilesRouteImport } from './routes/api/uploadthing-files'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppEditMealIdRouteImport } from './routes/_app/edit.$mealId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekRoute = AppWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingFilesRoute = ApiUploadthingFilesRouteImport.update({
  id: '/api/uploadthing-files',
  path: '/api/uploadthing-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditMealIdRoute = AppEditMealIdRouteImport.update({
  id: '/edit/$mealId',
  path: '/edit/$mealId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AppCalendarRoute
  '/history': typeof AppHistoryRoute
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRoute
  '/week': typeof AppWeekRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/uploadthing-files': typeof ApiUploadthingFilesRoute
  '/share/$token': typeof ShareTokenRoute
  '/edit/$mealId': typeof AppEditMealIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AppCalendarRoute
  '/history': typeof AppHistoryRoute
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRoute
  '/week': typeof AppWeekRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/uploadthing-files': typeof ApiUploadthingFilesRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/edit/$mealId': typeof AppEditMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/new': typeof AppNewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/week': typeof AppWeekRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/uploadthing-files': typeof ApiUploadthingFilesRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/edit/$mealId': typeof AppEditMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/calendar'
    | '/history'
    | '/new'
    | '/settings'
    | '/week'
    | '/api/uploadthing'
    | '/api/uploadthing-files'
    | '/share/$token'
    | '/edit/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/calendar'
    | '/history'
    | '/new'
    | '/settings'
    | '/week'
    | '/api/uploadthing'
    | '/api/uploadthing-files'
    | '/share/$token'
    | '/'
    | '/edit/$mealId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/calendar'
    | '/_app/history'
    | '/_app/new'
    | '/_app/settings'
    | '/_app/week'
    | '/api/uploadthing'
    | '/api/uploadthing-files'
    | '/share/$token'
    | '/_app/'
    | '/_app/edit/$mealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiUploadthingFilesRoute: typeof ApiUploadthingFilesRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week': {
      id: '/_app/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AppWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing-files': {
      id: '/api/uploadthing-files'
      path: '/api/uploadthing-files'
      fullPath: '/api/uploadthing-files'
      preLoaderRoute: typeof ApiUploadthingFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/edit/$mealId': {
      id: '/_app/edit/$mealId'
      path: '/edit/$mealId'
      fullPath: '/edit/$mealId'
      preLoaderRoute: typeof AppEditMealIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeekRoute: typeof AppWeekRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditMealIdRoute: typeof AppEditMealIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeekRoute: AppWeekRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditMealIdRoute: AppEditMealIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiUploadthingFilesRoute: ApiUploadthingFilesRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
