/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAjustesRouteImport } from './routes/_app/ajustes'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppHistorialRouteImport } from './routes/_app/historial'
import { Route as AppNuevaRouteImport } from './routes/_app/nueva'
import { Route as AppSemanaRouteImport } from './routes/_app/semana'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppEditarMealIdRouteImport } from './routes/_app/editar.$mealId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppNuevaRoute = AppNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppSemanaRoute = AppSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditarMealIdRoute = AppEditarMealIdRouteImport.update({
  id: '/editar/$mealId',
  path: '/editar/$mealId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ajustes': typeof AppAjustesRoute
  '/calendario': typeof AppCalendarioRoute
  '/historial': typeof AppHistorialRoute
  '/nueva': typeof AppNuevaRoute
  '/semana': typeof AppSemanaRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/share/$token': typeof ShareTokenRoute
  '/editar/$mealId': typeof AppEditarMealIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ajustes': typeof AppAjustesRoute
  '/calendario': typeof AppCalendarioRoute
  '/historial': typeof AppHistorialRoute
  '/nueva': typeof AppNuevaRoute
  '/semana': typeof AppSemanaRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/editar/$mealId': typeof AppEditarMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ajustes': typeof AppAjustesRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/nueva': typeof AppNuevaRoute
  '/_app/semana': typeof AppSemanaRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/editar/$mealId': typeof AppEditarMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ajustes'
    | '/calendario'
    | '/historial'
    | '/nueva'
    | '/semana'
    | '/api/uploadthing'
    | '/share/$token'
    | '/editar/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/ajustes'
    | '/calendario'
    | '/historial'
    | '/nueva'
    | '/semana'
    | '/api/uploadthing'
    | '/share/$token'
    | '/'
    | '/editar/$mealId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/ajustes'
    | '/_app/calendario'
    | '/_app/historial'
    | '/_app/nueva'
    | '/_app/semana'
    | '/api/uploadthing'
    | '/share/$token'
    | '/_app/'
    | '/_app/editar/$mealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nueva': {
      id: '/_app/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof AppNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/semana': {
      id: '/_app/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof AppSemanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/editar/$mealId': {
      id: '/_app/editar/$mealId'
      path: '/editar/$mealId'
      fullPath: '/editar/$mealId'
      preLoaderRoute: typeof AppEditarMealIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppNuevaRoute: typeof AppNuevaRoute
  AppSemanaRoute: typeof AppSemanaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditarMealIdRoute: typeof AppEditarMealIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppNuevaRoute: AppNuevaRoute,
  AppSemanaRoute: AppSemanaRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditarMealIdRoute: AppEditarMealIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
